redis:
  image: redis
  container_name: redis-url-short
  command: redis-server --requirepass setyourpassword
  ports:
    - 6379:6379

app:
  build: ./
  container_name: node-url-short
  links:
    - redis
  ports:
    - 80:3000