redis:
  image: redis:6.2.1-alpine
  container_name: redis-url-short
  command: redis-server --requirepass setyourpassword /usr/local/etc/redis/redis.conf
  volumes:
      - /tmp/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  ports:
    - 6379:6379

app:
  build: ./
  container_name: node-url-short
  links:
    - redis
  ports:
    - 80:3000