redis:
  image: redis
  container_name: redis-url-short
  command: bash -c "redis-server --requirepass setyourpassword && save 30 1"
  volumes:
      - /tmp/redis:/data
  ports:
    - 6379:6379

app:
  build: ./
  container_name: node-url-short
  links:
    - redis
  ports:
    - 80:3000